# Generated by Django 3.2.6 on 2021-08-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fcuser',
            new_name='user',
        ),
    ]
